### ISSUE TITLE
Suggestion: empty input should not run `kubectl`

### ISSUE THREAD

**Issue by walfie** [Mikulas/kubectl-repl#11]
Firstly, thanks a lot for this incredibly useful tool. One minor issue I have though, is that often in REPLs, I'll press <kbd>enter</kbd> a few times just to add some empty lines after the previous output. However, with `kubectl-repl`, pressing `enter` on an empty prompt runs `kubectl` by itself, which shows the verbose help documentation.

I guess I can accomplish the same thing by just typing `;` itself, but it would be nice if empty lines (and possibly just whitespace-only lines in general) could be a no-op.

**Comment by Mikulas** [comment]
Hi, thank you for the feedback. This is indeed a minor annoyance that I would like fixed as well. For me it mostly manifests when submitting something in an exec which then exits.

Until I get to it, which may in in the next few days, I will label this for others that may in interested in contributing.

**Comment by walfie** [comment]
I've never written Go code before until now, but I gave it a try: #12
