### ISSUE TITLE
Support for micro8s

### ISSUE THREAD

**Issue by GabrielC101** [Mikulas/kubectl-repl#14]
Microk8s provides it's own "kubectl", independent of whatever kubectl binary the system might have installed. It can be accessed via shell at "microk8s.kubectl".

I'm not sure this custom kubectl even supports contexts. It's purpose is to refer exclusively to the local microk8s engine.

**Comment by Mikulas** [comment]
I haven't installed microk8s but looking at the code, there seems to be a `microk8s.kubectl` script (https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/wrappers/microk8s-kubectl.wrapper) that invokes `${SNAP}/kubectl` with default args taken from https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/default-args/kubectl:
```
--kubeconfig=${SNAP_DATA}/credentials/client.config
```

Could you please try launching kubectl-repl with this kubeconfig? If there are additional hurdles I will investigate.

**Comment by Mikulas** [comment]
I believe this is resolved. Please reopen if that is not the case :)
