### ISSUE TITLE
GCP / GKE Not supported

### ISSUE THREAD

**Issue by darkzhadow** [Mikulas/kubectl-repl#8]
It looks like GCP is currently not supported

`2017/11/17 18:02:36 No Auth Provider found for name "gcp"`

Perhaps add missing plugin?
_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"

**Comment by Mikulas** [comment]
I have no experience with GCP. Why is the plugin required to communicate with the cluster? The api is surely the same, right?
Are you running the repl itself inside the GCP k8s cluster and authenticating by that?

**Comment by nicorikken** [comment]
I run into the same issue with the `oidc` provider. I get the impression the MR https://github.com/kubernetes/kubernetes/pull/41532 relates to the importing of these auths provider packages. I haven't looked into the implementation of `kubectl` and `kubectl-repl`, so I cannot offer more details at this moment.

**Comment by Mikulas** [comment]
Resolved in 2830fe35ab8a5c43d6e9243257abca1876ab4454 by relying completely on `kubectl` implementation.

**Comment by nicorikken** [comment]
Nice, I can confirm this fix works. Thanks a lot!
